### ISSUE TITLE
File not found in SCSS

### ISSUE THREAD

**Issue by martinszy** [mysociety/yournextmp-popit#367]
Contents of the style.css file after first run:

```css
Syntax error: File to import not found or unreadable: ../foundation/scss/foundation/functions.
              Load path: /home/vagrant/yournextmp/yournextmp-popit/candidates/static/candidates
        on line 1 of /home/vagrant/yournextmp/yournextmp-popit/candidates/static/candidates/style.scss

1: @import "../foundation/scss/foundation/functions";
2: 
3: $color-orange: #f97d3d;
4: $color-red: #c55e59;
5: $color-gold: #ba9f50;
6: $color-blue: #085184;

Backtrace:
/home/vagrant/yournextmp/yournextmp-popit/candidates/static/candidates/style.scss:1
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/import_node.rb:67:in `rescue in import'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/import_node.rb:45:in `import'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/import_node.rb:28:in `imported_file'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/import_node.rb:37:in `css_import?'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:217:in `visit_import'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `block in visit_children'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `map'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:53:in `visit_children'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:109:in `block in visit_children'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:121:in `with_environment'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:108:in `visit_children'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `block in visit'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:128:in `visit_root'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/base.rb:37:in `visit'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:100:in `visit'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/visitors/perform.rb:7:in `visit'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/tree/root_node.rb:20:in `render'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/engine.rb:315:in `_render'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/engine.rb:262:in `render'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/plugin/compiler.rb:362:in `update_stylesheet'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/plugin/compiler.rb:203:in `block in update_stylesheets'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/plugin/compiler.rb:201:in `each'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/plugin/compiler.rb:201:in `update_stylesheets'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/plugin.rb:81:in `update_stylesheets'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/exec.rb:443:in `watch_or_update'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/exec.rb:326:in `process_result'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/exec.rb:41:in `parse'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/lib/sass/exec.rb:21:in `parse!'
/home/vagrant/yournextmp/gems/gems/sass-3.2.19/bin/sass:13:in `<top (required)>'
/home/vagrant/yournextmp/gems/bin/sass:23:in `load'
/home/vagrant/yournextmp/gems/bin/sass:23:in `<main>'

**Comment by mhl** [comment]
I suspect that you didn't specify `--recursive` when cloning the repository, as the README suggests, so you'll need to run:

```
git submodule update --init
```

... to initialize them now.

**Comment by martinszy** [comment]
Thanks. That was it :)

**Comment by evz** [comment]
Any reason this was taken out of the README? It still seems to be a requirement.

**Comment by dracos** [comment]
It was moved to https://github.com/mysociety/yournextrepresentative/blob/master/docs/ynmp-vagrant.md linked to from the readme.
